[package]
name = "keyring_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "keyring_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34"
ed25519-dalek = { version = "2", features = ["rand_core"] }
blake3 = "1"
rand = "0.8"
